// <auto-generated />
using System;
using DM.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DM.Repository.Migrations
{
    [DbContext(typeof(DocumentDBContext))]
    partial class DocumentDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DM.Domain.Models.AggregateDocument", b =>
                {
                    b.Property<int>("MinParentDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("ChildDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("AggregateMetaDataModelID")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParentDocumentVersionId")
                        .HasColumnType("int");

                    b.HasKey("MinParentDocumentVersionId", "ChildDocumentVersionId");

                    b.HasIndex("AggregateMetaDataModelID");

                    b.HasIndex("ChildDocumentVersionId");

                    b.ToTable("AggregateDocument");
                });

            modelBuilder.Entity("DM.Domain.Models.AggregateMetaDataModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AggregateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChildMetadataModelId")
                        .HasColumnType("int");

                    b.Property<int>("ParentMetadataModelId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChildMetadataModelId");

                    b.HasIndex("ParentMetadataModelId", "ChildMetadataModelId", "AggregateName")
                        .IsUnique();

                    b.ToTable("AggregateMetaDataModel");
                });

            modelBuilder.Entity("DM.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("en");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb3fd05a-3c8d-4981-8e93-99f651655331",
                            Email = "admin@lit-co.net",
                            EmailConfirmed = false,
                            Language = "en",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LIT-CO.NET",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJrqzW/3Q2d9+2EozdLcWacbMFJYGgYQ1AEj4ULTX6igQSyjs/Yt2Fiia3qbKp9gGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5bde2999-7b55-48af-b0fd-83c47d06e453",
                            Email = "superadmin@lit-co.net",
                            EmailConfirmed = false,
                            Language = "en",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@LIT-CO.NET",
                            NormalizedUserName = "SUPER_ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEIgacxR6TeO89gZW/0GVGmmHVla7Jv8fqRf1Y6pe/oFczto4ymsQebVkkGbiEeXy5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "super_admin"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7343ae7-36ac-4751-b73d-558e08da1d1a",
                            Email = "user@lit-co.net",
                            EmailConfirmed = false,
                            Language = "en",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LIT-CO.NET",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAEAACcQAAAAEPjr6MhlAb5ZVm04AoZ6UZkHocSrvMa3WyWCpcQRax3rBOV/LcCdthYKSmqAv/Ksog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("DM.Domain.Models.Attachment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("AttachmentFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("CompoundModelID")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompoundModelID");

                    b.HasIndex("DocumentId", "CompoundModelID")
                        .IsUnique()
                        .HasFilter("[CompoundModelID] IS NOT NULL");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("DM.Domain.Models.BoolValue", b =>
                {
                    b.Property<int>("MinDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MetaDataAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<bool?>("Value")
                        .HasColumnType("bit");

                    b.HasKey("MinDocumentVersionId", "MetaDataAttributeId");

                    b.HasIndex("MetaDataAttributeId");

                    b.ToTable("BoolValue");
                });

            modelBuilder.Entity("DM.Domain.Models.CompoundModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("MetaDataModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MetaDataModelID");

                    b.ToTable("CompoundModel");
                });

            modelBuilder.Entity("DM.Domain.Models.DataType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("DataTypeName")
                        .IsUnique();

                    b.ToTable("DataType");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataTypeName = "bool"
                        },
                        new
                        {
                            ID = 2,
                            DataTypeName = "date"
                        },
                        new
                        {
                            ID = 3,
                            DataTypeName = "decimal"
                        },
                        new
                        {
                            ID = 4,
                            DataTypeName = "double"
                        },
                        new
                        {
                            ID = 5,
                            DataTypeName = "int"
                        },
                        new
                        {
                            ID = 6,
                            DataTypeName = "string"
                        });
                });

            modelBuilder.Entity("DM.Domain.Models.DateValue", b =>
                {
                    b.Property<int>("MinDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MetaDataAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Value")
                        .HasColumnType("datetime2");

                    b.HasKey("MinDocumentVersionId", "MetaDataAttributeId");

                    b.HasIndex("MetaDataAttributeId");

                    b.ToTable("DateValue");
                });

            modelBuilder.Entity("DM.Domain.Models.DecimalValue", b =>
                {
                    b.Property<int>("MinDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MetaDataAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,5)");

                    b.HasKey("MinDocumentVersionId", "MetaDataAttributeId");

                    b.HasIndex("MetaDataAttributeId");

                    b.ToTable("DecimalValue");
                });

            modelBuilder.Entity("DM.Domain.Models.Document", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LatestVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MetaDataModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LatestVersionId")
                        .IsUnique()
                        .HasFilter("[LatestVersionId] IS NOT NULL");

                    b.HasIndex("MetaDataModelId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentClassName")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DocumentClass");
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DocumnetScan")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("MaxDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MinDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MinDocumentVersionId");

                    b.ToTable("DocumentScan");
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentSet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentSet");
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentSet_Document", b =>
                {
                    b.Property<int>("DocumentSetId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.HasKey("DocumentSetId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentSet_Document");
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentVersion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VersionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentVersion");
                });

            modelBuilder.Entity("DM.Domain.Models.DoubleValue", b =>
                {
                    b.Property<int>("MinDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MetaDataAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("MinDocumentVersionId", "MetaDataAttributeId");

                    b.HasIndex("MetaDataAttributeId");

                    b.ToTable("DoubleValue");
                });

            modelBuilder.Entity("DM.Domain.Models.IntValue", b =>
                {
                    b.Property<int>("MinDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MetaDataAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("MinDocumentVersionId", "MetaDataAttributeId");

                    b.HasIndex("MetaDataAttributeId");

                    b.ToTable("IntValue");
                });

            modelBuilder.Entity("DM.Domain.Models.MetaDataAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DataTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDataAttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetaDataModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DataTypeID");

                    b.HasIndex("MetaDataModelID");

                    b.ToTable("MetaDataAttribute");
                });

            modelBuilder.Entity("DM.Domain.Models.MetaDataModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentClassId")
                        .HasColumnType("int");

                    b.Property<string>("MetaDataModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentClassId");

                    b.HasIndex("MetaDataModelName")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MetaDataModel");
                });

            modelBuilder.Entity("DM.Domain.Models.RecursiveDocumentSet", b =>
                {
                    b.Property<int>("ParentDocumentSetId")
                        .HasColumnType("int");

                    b.Property<int>("ChildDocumentSetId")
                        .HasColumnType("int");

                    b.HasKey("ParentDocumentSetId", "ChildDocumentSetId");

                    b.HasIndex("ChildDocumentSetId");

                    b.ToTable("RecursiveDocumentSet");
                });

            modelBuilder.Entity("DM.Domain.Models.StringValue", b =>
                {
                    b.Property<int>("MinDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MetaDataAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDocumentVersionId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MinDocumentVersionId", "MetaDataAttributeId");

                    b.HasIndex("MetaDataAttributeId");

                    b.ToTable("StringValue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "3cf622c2-1205-4c47-b0ec-c2f5e3ef3cf0",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "9a1c35c1-8850-47aa-ac6f-0a1bf715a44d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "fa85dee0-71a8-43e8-a68a-f6680bfbac84",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DM.Domain.Models.AggregateDocument", b =>
                {
                    b.HasOne("DM.Domain.Models.AggregateMetaDataModel", "AggregateMetaDataModel")
                        .WithMany("AggregateDocuments")
                        .HasForeignKey("AggregateMetaDataModelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "ChildDocumentVersion")
                        .WithMany("ParentDocumentVersions")
                        .HasForeignKey("ChildDocumentVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "MinParentDocumentVersion")
                        .WithMany("ChildDocumentVersions")
                        .HasForeignKey("MinParentDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.AggregateMetaDataModel", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataModel", "ChildMetaDataModel")
                        .WithMany("ParentMetaDataModels")
                        .HasForeignKey("ChildMetadataModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.MetaDataModel", "ParentMetaDataModel")
                        .WithMany("ChildMetaDataModels")
                        .HasForeignKey("ParentMetadataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.Attachment", b =>
                {
                    b.HasOne("DM.Domain.Models.CompoundModel", "CompoundModel")
                        .WithMany("Attachments")
                        .HasForeignKey("CompoundModelID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DM.Domain.Models.Document", "Document")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.BoolValue", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataAttribute", "MetaDataAttribute")
                        .WithMany("BoolValues")
                        .HasForeignKey("MetaDataAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("BoolValues")
                        .HasForeignKey("MinDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.CompoundModel", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataModel", "MetaDataModel")
                        .WithMany("CompoundModels")
                        .HasForeignKey("MetaDataModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DateValue", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataAttribute", "MetaDataAttribute")
                        .WithMany("DateValues")
                        .HasForeignKey("MetaDataAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("DateValues")
                        .HasForeignKey("MinDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DecimalValue", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataAttribute", "MetaDataAttribute")
                        .WithMany("DecimalValues")
                        .HasForeignKey("MetaDataAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("DecimalValues")
                        .HasForeignKey("MinDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.Document", b =>
                {
                    b.HasOne("DM.Domain.Models.DocumentVersion", "LatestDocumentVersion")
                        .WithOne()
                        .HasForeignKey("DM.Domain.Models.Document", "LatestVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DM.Domain.Models.MetaDataModel", "MetaDataModel")
                        .WithMany("Documents")
                        .HasForeignKey("MetaDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentClass", b =>
                {
                    b.HasOne("DM.Domain.Models.ApplicationUser", "User")
                        .WithMany("DocumentClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentScan", b =>
                {
                    b.HasOne("DM.Domain.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("DocumnetScans")
                        .HasForeignKey("MinDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentSet", b =>
                {
                    b.HasOne("DM.Domain.Models.ApplicationUser", "User")
                        .WithMany("DocumentSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentSet_Document", b =>
                {
                    b.HasOne("DM.Domain.Models.Document", "Document")
                        .WithMany("Set_Documents")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentSet", "DocumentSet")
                        .WithMany("Set_Documents")
                        .HasForeignKey("DocumentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DocumentVersion", b =>
                {
                    b.HasOne("DM.Domain.Models.Document", "Document")
                        .WithMany("DocumentVersions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.ApplicationUser", "User")
                        .WithMany("DocumentVersions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.DoubleValue", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataAttribute", "MetaDataAttribute")
                        .WithMany("DoubleValues")
                        .HasForeignKey("MetaDataAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("DoubleValues")
                        .HasForeignKey("MinDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.IntValue", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataAttribute", "MetaDataAttribute")
                        .WithMany("IntValues")
                        .HasForeignKey("MetaDataAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("IntValues")
                        .HasForeignKey("MinDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.MetaDataAttribute", b =>
                {
                    b.HasOne("DM.Domain.Models.DataType", "DataType")
                        .WithMany("MetaDataAttributes")
                        .HasForeignKey("DataTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.MetaDataModel", "MetaDataModel")
                        .WithMany("MetaDataAttributes")
                        .HasForeignKey("MetaDataModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.MetaDataModel", b =>
                {
                    b.HasOne("DM.Domain.Models.DocumentClass", "DocumentClass")
                        .WithMany("MetaDataModels")
                        .HasForeignKey("DocumentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.ApplicationUser", "User")
                        .WithMany("MetaDataModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.RecursiveDocumentSet", b =>
                {
                    b.HasOne("DM.Domain.Models.DocumentSet", "ChildDocumentSet")
                        .WithMany("ParentDocumentsSets")
                        .HasForeignKey("ChildDocumentSetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentSet", "ParentDocumentSet")
                        .WithMany("ChildDocumentsSets")
                        .HasForeignKey("ParentDocumentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DM.Domain.Models.StringValue", b =>
                {
                    b.HasOne("DM.Domain.Models.MetaDataAttribute", "MetaDataAttribute")
                        .WithMany("StringValues")
                        .HasForeignKey("MetaDataAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("StringValues")
                        .HasForeignKey("MinDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DM.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DM.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DM.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DM.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
